function skipIt = skipNativeStackPrint(library_name, function_name, file_name)
    libraryToSkip = {'libpthread.so.0','libmwmcr.so','mwm_interpreter_builtinimpl.so','sf.mexa64','mwm_interpreter_builtinimpl.so','mwlibmwsl_services_builtinimpl.so'}; 
    %    ,'libmwsimulink.so','libmwsl_graphical_classes.so','libmwsl_services.so'};
    if contains(library_name,libraryToSkip)%~isequal(library_name,'libmwstateflow.so')       
        skipIt = true;
        return;
    end
    

    if startsWith(function_name,'mcr::') ...  
            || startsWith(function_name,'foundation::')   ...
            || startsWith(function_name,'SF::Private')   ...
            || startsWith(function_name,'SF::Access_Method')   ...
            || startsWith(function_name,'mexFunction')   ...
            || startsWith(function_name,'SF::sf_mexFunction')   ...
            || startsWith(function_name,'SF::safe_mex_call_matlab')   ...
            || startsWith(function_name,'slsvInternal')   ...
            || startsWith(function_name,'slsvFEVAL')   ...
            || startsWith(function_name,'SF::try_mexFunction')   ...
            || startsWith(function_name,'slsvGetNativeCallStack')   ...
            || startsWith(function_name,'SF::slsf')   ...
            || startsWith(function_name,'CallFcn_MLCommand::operator')   ...
            || startsWith(function_name,'foundation::')   ...
            || startsWith(function_name,'CMatlabCommand::execute')   ...
            || startsWith(function_name,'foundation::')   ...
            || startsWith(function_name,'foundation::')   ...
            || startsWith(function_name,'foundation::')   ...
            || startsWith(function_name,'mcr::')
        skipIt = true;
        return;
    end
    skipIt = false;
end