#!/usr/bin/python

import os.path
import sys

if __name__ == '__main__':
  if len(sys.argv)<2:
    " Invoke sbroot!"
    command = "sbroot"
    proc = os.popen(command)
    sbroot = proc.read().split('\n')[0]
  else:
    suffix = sys.argv[1]
    sbroot = '/local-ssd/mwood/Aslrtw' + suffix
  print sbroot
  
  
