@ECHO OFF
REM Find the root of the current sandbox.
for /f "tokens=*" %%i in ('sbroot') do set sbrootDir=%%i
echo Using sandbox: %sbrootDir%

cd "%sbrootDir%"

REM Create a .gitignore file that will ignore the solution and project files generated by nativeproj for the current sandbox.
for %%* in (.) do set CurrentDirName=%%~n*
touch .gitignore
attrib -r .gitignore
echo # Ignore naiveproj Visual Studio generated file. Do not submit this file.>.gitignore
echo native_*.props>>.gitignore
echo native_*.sln>>.gitignore
echo native_*.vcxproj>>.gitignore
echo native_*.vcxproj.filters>>.gitignore
echo native_*.vcxproj.user>>.gitignore
echo native_*.vcxproj.tmp>>.gitignore
echo native_*.vcxproj.filters.tmp>>.gitignore
echo native_*.vcxproj.user.tmp>>.gitignore
echo devenv.cmd>>.gitignore
echo devenv12.cmd>>.gitignore
echo devenv13.cmd>>.gitignore
echo devenv15.cmd>>.gitignore

echo %CurrentDirName%.sdf>>.gitignore
echo %CurrentDirName%.sln>>.gitignore
echo %CurrentDirName%.suo>>.gitignore
REM Also, set the .gitignore file in read-only mode to ease the non submission of this file.
attrib +r .gitignore

echo Create a fastbuild file for the Stateflow code base to enable bundle build using nativeproj.
echo touch matlab\toolbox\stateflow\src\stateflow\vcproj.defn.fastbuild
echo attrib +r matlab\toolbox\stateflow\src\stateflow\vcproj.defn.fastbuild

REM call sbnativeproj -no3p -nobb toolbox/stateflow/src/stateflow:notest toolbox/stateflow/src/sf_sfun:notest toolbox/stateflow/src/sfdi_datamodel:notest  src/cg_ir:nopch:notest src/cgir_cgel:notest src/cgir_xform:notest toolbox/stateflow/src/sf_editor:notest  toolbox/stateflow/src/sfdi_datamodel_mi
REM call sbnativeproj -no3p -nobb toolbox/stateflow/src/stateflow:notest
call sbnativeproj -no3p -nobb toolbox/stateflow/src/sf_xform:notest toolbox/stateflow/src/stateflow:notest 
REM call sbnativeproj -no3p -nobb toolbox/stateflow/src/stateflow:notest 
REM src/cg_ir:nopch:notest src/cgir_cgel:notest src/cgir_xform:notest 
REM src/cg_ir:nopch:notest src/cgir_cgel:notest src/cgir_xform:notest src/shared_simulink_lang_blocks:notest src/sl_compile:notest
REM call sbnativeproj -no3p -nobb toolbox/stateflow/src/stateflow:notest src/cgir_cpp_emitter:notest src/cg_ir:notest
REM toolbox/stateflow/src/cg_ir:nopch:notest
REM src/rtwcg:nopch:notest src/smaht:nopch:notest
REM src/cg_ir:nopch:notest src/cgir_cgel:notest src/cgir_xform:notest toolbox/stateflow/src/sfdi_datamodel
echo Finished generating projects.

REM Cannot have src/m_interpreter now...

echo Now fixing the solution

sed "/^$/d" %CurrentDirName%.sln > temp.tmp
mv temp.tmp %CurrentDirName%.sln

REM echo Compile the solution!
REM C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe %CurrentDirName%.sln

rm -f matlab\bin\win64\*.pdb

echo Finished preparing sandbox.

